login_base:
  creds:
    username: ''
    password: ''

cookie_base:
  cookie_file: 'www.popmart.com.cookies.json'
  storage_file: 'www.popmart.com.storage.json'

locators:
  login_page: 'https://www.popmart.com/us/user/login?redirect=%2Faccount'
  agreement: '.policy_acceptBtn__ZNU71'
  login_field: '.index_loginInput__HBgjq'
  login_btn: '.index_loginButton__O6r8l'
  password_field: '#password'
  buy_now: '.index_usBtn__2KlEx.index_red__kx6Ql.index_btnFull__F7k90'
  go_to_cart: '.ant-btn.ant-btn-primary.ant-btn-dangerous.index_noticeFooterBtn__XpFsc'
  checkout: '.ant-btn.ant-btn-primary.ant-btn-dangerous.index_checkout__V9YPC'
  checkbox: '.index_checkbox__w_166'
  pay: '#__next > div > div > div.layout_pcLayout__49ZwP > div.index_container__SNJGT > div.index_leftContainer__3Roux > div > button'
  ordering: '#buttons-container > div > div.paypal-button-row.paypal-button-number-0.paypal-button-layout-horizontal.paypal-button-number-multiple.paypal-button-env-production.paypal-button-color-black.paypal-button-text-color-white.paypal-logo-color-white.paypal-button-shape-rect'

target_product: 'https://www.popmart.com/us/products/1372/THE-MONSTERS---Have-a-Seat-Vinyl-Plush-Blind-Box'